build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
labels:
  org.opencontainers.image.title: "Strix Camera Discovery"
  org.opencontainers.image.description: "Smart IP camera stream discovery system"
  org.opencontainers.image.source: "https://github.com/eduard256/Strix"
  org.opencontainers.image.licenses: "MIT"
args:
  STRIX_VERSION: "1.0.0"
